site_name: Orchard Core Documentation
theme:
  name: material
  custom_dir: src/docs/theme
  logo: docs/assets/images/orchard-logo.png
  favicon: docs/assets/images/favicon.png
  features:
    - navigation.footer
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  static_templates:
    - 404.html

extra:
  social:
    - icon: fontawesome/solid/leaf
      link: https://orchardcore.net
    - icon: fontawesome/brands/github-alt
      link: https://github.com/OrchardCMS/OrchardCore
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OrchardCMS

# Repository
repo_name: OrchardCMS/OrchardCore
repo_url: https://github.com/OrchardCMS/OrchardCore
edit_uri: edit/main/src/

# Options
docs_dir: src

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  # - mdx_truly_sane_lists:
  #     nested_indent: 2
  #     truly_sane: True
  - pymdownx.b64
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
#  - markdown.extensions.nl2br

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - exclude:
      glob:
        # Excluding the large node folder with all its MD files. We can't exclude everything apart from docs because there are links to e.g. C# files too.
        - "*node_modules*"

# Page tree
nav:
  - About Orchard Core: README.md
  - Getting started:
      - Create a CMS Web application: docs/getting-started/README.md
      - Configure Preview package source: docs/getting-started/preview-package-source.md
      - Recipes and Starter Themes: docs/getting-started/starter-recipes.md
      - Code Generation Templates: docs/getting-started/templates/README.md
      - Create a Theme: docs/getting-started/theme.md
  - Glossary:
      - Terms and Concepts: docs/glossary/README.md
  - How-to guides:
      - Follow the Guides: docs/guides/README.md
      - Create a modular application: docs/guides/create-modular-application-mvc/README.md
      - Create a website: docs/guides/create-cms-application/README.md
      - Leverage CSPROJ meta information: docs/guides/leverage-csproj-meta-info/README.md
      - Create a Decoupled CMS site: docs/guides/decoupled-cms/README.md
      - Add an admin menu: docs/guides/add-admin-menu/README.md
      - Implement Full Text search: docs/guides/implement-fulltext-search/README.md
      - Install localization files: docs/guides/install-localization-files/README.md
      - Integrate Facebook plugins: docs/guides/integrate-facebook-plugins/README.md
      - Run code on startup: docs/guides/run-code-on-startup/README.md
      - Create a custom admin theme: docs/guides/create-admin-theme/README.md
      - Customize encoding settings: docs/guides/encoding-settings/README.md
      - Understanding Content Definitions Stores: docs/guides/content-definitions/README.md
      - Change password configuration: docs/guides/password-configuration/README.md
      - Change lockout configuration: docs/guides/lockout-configuration/README.md
      - Microsoft Entra ID (Azure AD) integration: docs/guides/microsoft-entra-id-integration/README.md
      - Create a Liquid Widget: docs/guides/create-liquid-widget/README.md
      - Query Content Items Based on Taxonomy: docs/guides/query-content-items-based-on-taxonomy/README.md
      - Gulp pipeline: docs/guides/gulp-pipeline/README.md
  - Key Topics:
      - Manage your Content: docs/topics/content-management/README.md
      - Content Relationships: docs/topics/content-relationships/README.md
      - Customize the Display: docs/topics/display/README.md
      - Localize your site: docs/topics/localize/README.md
      - Handle the Media: docs/topics/media/README.md
      - Navigate between pages: docs/topics/navigation/README.md
      - Query and Search data: docs/topics/search/README.md
      - Secure your application: docs/topics/security/README.md
      #        - Data: docs/topics/data/README.md
      #        - Configuration: docs/topics/configuration/README.md
      - Workflows: docs/topics/workflows/README.md
      - Contributing to the docs: docs/topics/docs-contributions/README.md
      - Publishing a new release: docs/topics/publishing-releases/README.md
      - Using Docker: docs/topics/docker/README.md
      - Using local NuGet packages: docs/topics/local-nuget-packages/README.md
      - Managing the Orchard Core Red Hat Ecosystem Catalog certification:  docs/topics/red-hat-ecosystem-catalog-certification/README.md
  - Reference:
      - docs/reference/README.md
      - CMS Modules:
          - Content Types: docs/reference/modules/ContentTypes/README.md
          - Content Parts:
              - Add Parts to your Content: docs/reference/modules/ContentParts/README.md
              - Title: docs/reference/modules/Title/README.md
              - Autoroute: docs/reference/modules/Autoroute/README.md
              - Alias: docs/reference/modules/Alias/README.md
              - Html: docs/reference/modules/Html/README.md
              - Markdown: docs/reference/modules/Markdown/README.md
              - List: docs/reference/modules/Lists/README.md
              - Flow: docs/reference/modules/Flow/README.md
              - Bag: docs/reference/modules/Flow/BagPart.md
              - Publish Later: docs/reference/modules/PublishLater/README.md
              - SEO Meta: docs/reference/modules/Seo/README.md
          - Content Fields: docs/reference/modules/ContentFields/README.md
          - Content Preview: docs/reference/modules/ContentPreview/README.md
          - Content Localization: docs/reference/modules/ContentLocalization/README.md
          - Layers: docs/reference/modules/Layers/README.md
          - Widgets: docs/reference/modules/Widgets/README.md
          - Forms: docs/reference/modules/Forms/README.md
          - Templates: docs/reference/modules/Templates/README.md
          - Placements: docs/reference/modules/Placements/README.md
          - Themes: docs/reference/modules/Themes/README.md
          - Liquid: docs/reference/modules/Liquid/README.md
          - Indexing: docs/reference/modules/Indexing/README.md
          - SQL Indexing: docs/reference/modules/SQLIndexing/README.md
          - Lucene: docs/reference/modules/Lucene/README.md
          - Elasticsearch: docs/reference/modules/Elasticsearch/README.md
          - Queries: docs/reference/modules/Queries/README.md
          - Media:
              - Media: docs/reference/modules/Media/README.md
              - Media Slugify: docs/reference/modules/Media.Slugify/README.md
              - Media Amazon S3: docs/reference/modules/Media.AmazonS3/README.md
              - Media Azure: docs/reference/modules/Media.Azure/README.md
          - ReCaptcha: docs/reference/modules/ReCaptcha/README.md
          - Resources: docs/reference/modules/Resources/README.md
          - Rules: docs/reference/modules/Rules/README.md
          - Shortcodes: docs/reference/modules/Shortcodes/README.md
          - Sitemaps: docs/reference/modules/Sitemaps/README.md
          - SMS: docs/reference/modules/Sms/README.md
          - Spatial: docs/reference/modules/Spatial/README.md
          - XML-RPC: docs/reference/modules/XmlRpc/README.md
          - Menu: docs/reference/modules/Menu/README.md
          - Navigation: docs/reference/modules/Navigation/README.md
          - Admin: docs/reference/modules/Admin/README.md
          - Admin Dashboard: docs/reference/modules/AdminDashboard/README.md
          - Admin Menu: docs/reference/modules/AdminMenu/README.md
          - Taxonomies: docs/reference/modules/Taxonomies/README.md
          - Authentication:
              - Microsoft: docs/reference/modules/Microsoft.Authentication/README.md
              - Facebook: docs/reference/modules/Facebook/README.md
              - Twitter: docs/reference/modules/Twitter/README.md
              - GitHub: docs/reference/modules/GitHub/README.md
              - Google: docs/reference/modules/Google/README.md
          - Users:
              - Overview: docs/reference/modules/Users/README.md
              - Custom User Settings: docs/reference/modules/Users/CustomUserSettings/README.md
              - Notifications: docs/reference/modules/Notifications/README.md
              - Ticket store: docs/reference/modules/Users/TicketStore.md
          - Home Route: docs/reference/modules/HomeRoute/README.md
          - Feeds: docs/reference/modules/Feeds/README.md
      - Core Modules:
          - Audit Trail: docs/reference/modules/AuditTrail/README.md
          - Auto Setup: docs/reference/modules/AutoSetup/README.md
          - Features: docs/reference/modules/Features/README.md
          - Contents: docs/reference/modules/Contents/README.md
          - Configuration: docs/reference/core/Configuration/README.md
          - Cors: docs/reference/modules/Cors/README.md
          - Custom Settings: docs/reference/modules/CustomSettings/README.md
          - Deployment: docs/reference/modules/Deployment/README.md
          - Placement: docs/reference/core/Placement/README.md
          - Data: docs/reference/core/Data/README.md
          - Data Migrations: docs/reference/modules/Migrations/README.md
          - Dynamic Cache: docs/reference/modules/DynamicCache/README.md
          - Email: docs/reference/modules/Email/README.md
          - GraphQL: docs/reference/modules/Apis.GraphQL/README.md
          - GraphQL queries: docs/reference/core/Apis.GraphQL.Abstractions/README.md
          - Health Check: docs/reference/modules/HealthChecks/README.md
          - HTTPS: docs/reference/modules/Https/README.md
          - Key Vault (Azure): docs/reference/core/KeyVault.Azure/README.md
          - Localization: docs/reference/modules/Localize/README.md
          - Logging Serilog: docs/reference/core/Logging.Serilog/README.md
          - Mini Profiler: docs/reference/modules/MiniProfiler/README.md
          - Modules: docs/reference/core/Modules/README.md
          - OpenId: docs/reference/modules/OpenId/README.md
          - Razor Helpers: docs/reference/core/Razor/README.md
          - Recipes: docs/reference/modules/Recipes/README.md
          - Redis: docs/reference/modules/Redis/README.md
          - Remote Deployment: docs/reference/modules/Deployment.Remote/README.md
          - Response Compression: docs/reference/modules/ResponseCompression/README.md
          - Roles: docs/reference/modules/Roles/README.md
          - Sanitizer: docs/reference/core/Sanitizer/README.md
          - Scripting: docs/reference/modules/Scripting/README.md
          - Security: docs/reference/modules/Security/README.md
          - Setup: docs/reference/modules/Setup/README.md
          - Shells: docs/reference/core/Shells/README.md
          - Tenants: docs/reference/modules/Tenants/README.md
          - Workflows: docs/reference/modules/Workflows/README.md
          - DataProtection (Azure Storage): docs/reference/modules/DataProtection.Azure/README.md
          - Background Tasks: docs/reference/modules/BackgroundTasks/README.md
          - Reverse Proxy: docs/reference/modules/ReverseProxy/README.md
  - Resources:
      - Learning: docs/resources/README.md
      - Tutorials: docs/resources/tutorials/README.md
      - Development Tools: docs/resources/development-tools/README.md
      - Meeting: docs/resources/meeting/README.md
      - Branding: docs/resources/branding/README.md
      - Libraries: docs/resources/libraries/README.md
      - Owners: docs/resources/owners/README.md
      - Workshops: docs/resources/workshops/README.md
  - Releases:
      - 1.8.0: docs/releases/1.8.0.md
      - 1.7.2: docs/releases/1.7.2.md
      - 1.7.1: docs/releases/1.7.1.md
      - 1.7.0: docs/releases/1.7.0.md
      - 1.6.0: docs/releases/1.6.0.md
      - 1.5.0: docs/releases/1.5.0.md
      - 1.4.0: docs/releases/1.4.0.md
      - 1.3.0: docs/releases/1.3.0.md
      - 1.2.2: docs/releases/1.2.2.md
      - 1.2.1: docs/releases/1.2.1.md
      - 1.2.0: docs/releases/1.2.0.md
      - 1.1.0: docs/releases/1.1.0.md
      - 1.0.0: docs/releases/1.0.0.md
      - 1.0.0-rc2: docs/releases/1.0.0-rc2.md
      - 1.0.0-rc1: docs/releases/1.0.0-rc1.md
      - 1.0.0-beta3: docs/releases/1.0.0-beta3.md
      - 1.0.0-beta2: docs/releases/1.0.0-beta2.md
      - 1.0.0-beta1: docs/releases/1.0.0-beta1.md
  - Community:
      - Overview: docs/community/README.md
      - Honorable Members:
          - Jean-Thierry Kéchichian: docs/community/jean-thierry/README.md
