name: Functional Tests - all Databases
on:
  # manual trigger
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test_functional_mvc:
    name: Functional Tests - MVC
    runs-on: ubuntu-latest
    container:
      image: cypress/included:9.6.1
    steps:
    - uses: actions/checkout@v3
      # We need to install dotnet in the docker container.
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - uses: actions/setup-node@v3
      with:
        node-version: "15"
    - name: Functional Tests
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run mvc:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: functional-mvc-screenshots
        path: test/OrchardCore.Tests.Functional/mvc-tests/cypress/screenshots
        retention-days: 3
  
  test_functional_cms_sqlite:
    name: Functional Tests - CMS Sqlite
    runs-on: ubuntu-latest
    container:
      image: cypress/included:9.6.1
    steps:
    - uses: actions/checkout@v3
      # We need to install dotnet in the docker container.
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Functional Tests
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run cms:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: functional-cms-sqlite-failure
        path: |
          test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data/logs
        retention-days: 3
  
  test_functional_cms_postgresql:
    name: Functional Tests - CMS Postgres
    runs-on: ubuntu-latest
    container:
      image: cypress/included:9.6.1
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: app
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      OrchardCore__ConnectionString: "User ID=postgres;Password=admin;Host=postgres;Port=5432;Database=app;"
      OrchardCore__DatabaseProvider: "Postgres"
    steps:
    - uses: actions/checkout@v3
      # We need to install dotnet in the docker container.
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Functional Tests
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run cms:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: functional-cms-postgresql-failure
        path: |
          test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data/logs
        retention-days: 3

  test_functional_cms_mysql:
    name: Functional Tests - CMS MySql
    runs-on: ubuntu-latest
    container:
      image: cypress/included:9.6.1
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test123
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      OrchardCore__ConnectionString: "server=mysql;uid=root;pwd=test123;database=test"
      OrchardCore__DatabaseProvider: "MySql"
    steps:
    - uses: actions/checkout@v3
      # We need to install dotnet in the docker container.
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Functional Tests
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run cms:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: functional-cms-mysql-failure
        path: |
          test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data/logs
        retention-days: 3

  test_functional_cms_mssql:
    name: Functional Tests - CMS SqlServer 2019
    runs-on: ubuntu-latest
    container:
      image: cypress/included:9.6.1
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
    env:
      OrchardCore__ConnectionString: "Server=mssql;Database=tempdb;User Id=sa;Password=Password12!;Encrypt=False"
      OrchardCore__DatabaseProvider: "SqlConnection"
    steps:
    - uses: actions/checkout@v3
      # We need to install dotnet in the docker container.
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Functional Tests
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run cms:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: functional-cms-mssql-failure
        path: |
          test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data/logs
        retention-days: 3
