name: Unit Tests - MacOS
on:
# manual trigger
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: macos-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      run: |
        dotnet build -c Release -f net7.0
        dotnet build -c Release -f net6.0
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
